config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :stores do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  
  get 'pages/about'

  get 'pages/contact'

  root 'stores#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :store

	validates :rating, :comment, presence: true
	validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: "Can only be a whole number between 1 and 5"
  	}
end

app/models/store.rb
class Store < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	searchkick

	has_many :reviews

	validates :name, :address, :phone, :website, presence: true
	validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
  		message: "Must be in the format (123) 456-7890" }
  	validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
  		message: "Must start with http:// or https://" }
  	validates :address, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
  		message: "Must be in the format 350 Fifth Avenue, New York, NY 10118" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_store
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.store_id = @store.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @store, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @store, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @store, notice: 'Review was successfully deleated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_store
      @store = Store.find(params[:store_id])
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show]

  def search
  if params[:search].present?
    @stores = Store.search(params[:search])
  else
    @stores = Store.all
  end
end

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @reviews = Review.where(store_id: @store.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :phone, :website, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
   	content_for(:pagetitle) { page_title + ' | Seattle Cannabis Guide ' }
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
        
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JQuery -->
 	<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/layouts/_footer.html.erb
<p>Copyright 2015 Seattle Cannabis Guide</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Seattle Cannabis Guide", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
        <%= form_tag search_stores_path, method: :get, class: "navbar-form navbar-left" do %>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <%= submit_tag  "Search", name: nil, class: "btn btn-success" %>
          </p>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:pagetitle) %></title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container-fluid">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %> 
    
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<% title 'About Us' %>

<h1>Seattle Cannabis Guide</h1>
<p>We created the <%= link_to "Seattle Cannabis Guide", "http://www.seattlecannabisguide.com" %> to help people find the best cannabis retailers in your area</p>

<p>Use the Search bar above to find a store near you!</p>

<p>Have a favorite store or one you would like to recommend?  Leave a review so that everyone will know the best places to shop!</p>

app/views/pages/contact.html.erb
<% title 'Contact Us' %>

<h1>Seattle Cannabis Contact</h1>
<p>Contact us with any questions you may have</p>

app/views/reviews/_form.html.erb
<%= form_for([@store, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>
      
      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="star-rating"></div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/seattlecannabisguide/stars',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', store_path(@store) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', store_path(@store) %>

app/views/stores/_form.html.erb
<%= form_for(@store, :html => { multipart: true}) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h4>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "New Cannabis Store" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "123 Front Street, Seattle, WA 98027" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control", placeholder: "http://www.myweedstore.com" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store, class: "btn btn-link" %> |
<%= link_to 'Back', stores_path, class: "btn btn-link"  %>

app/views/stores/index.html.erb
<% title 'Find Marijuana Retail Stores' %>


<div class="jumbotron">
  <h2>The best way to find great area marijuana retail stores</h2>
  <h3>Explore favorite retail stores, smoke shops, and dispensaries in your area.<br>
    Leave reviews and ratings for your fellow cannabis lovers</h3>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store %></td>
        <td><%= store.address %></td>
        <td><%= store.phone %></td>
        <td><%= link_to store.website, store.website, class: "btn btn-link" %></td>
          <% if user_signed_in? && current_user.admin? %>
            <td><%= link_to 'Edit', edit_store_path(store), class: "btn btn-link"  %></td>
            <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Store', new_store_path, class: "btn btn-link"  %>
<% end %>

<br>
<br>

<div align="center">
<%= image_tag "https://s3.amazonaws.com/seattlecannabisguide/Seattle.jpg" %>
</div>

<br>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path, class: "btn btn-link"  %>

app/views/stores/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store %></td>
        <td><%= store.address %></td>
        <td><%= store.phone %></td>
        <td><%= link_to store.website, store.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_store_path(store), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/show.html.erb
<% title @store.name %>

<div class="row">
	<div class="col-md-4">
		<%= image_tag @store.image_url %>
<br><br>
<p>
  <h3>
  	<%= @store.name %>
  </h3>
  <div class="star-rating" data-score= <%= @avg_rating %> ></div>
  <p><%= "#{@reviews.length} reviews" %></p>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @store.website, @store.website, class: "btn btn-link" %>
</p>

<%= link_to 'Write a Review!', new_store_review_path(@store), class: "btn btn-success" %>
  <br>
  <br>
  <iframe
    width="300"
    height="300"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB6ggKmeMwJXiYmAH5A2Dlyec872HVFkoI
      &q=<%= @store.address.parameterize %>&zoom=14">
  </iframe>

	</div>

	<div class-"col-md-8">
    <h3>Reviews</h3>
		<% if @reviews.blank? %>
      		<h3>There are no reviews for this store.<br> Be the first to write a review!</h3>
    	<% else %>
    	<div class="table-responsive">
    		<table class="table table-condensed">
          <thead>
            <tr>
              <th class="col-md-3"></th>
              <th class="col-md-9"></th>
            </tr>
          </thead>

  				<tbody>
  				  <% @reviews.each do |review| %>
    				  <tr>
                  <td>
                    <h5><strong>
                     <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                    </strong></h5>
                    <p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
                  </td>
      					  <td>
     					     <div class="star-rating" data-score= <%= review.rating %> ></div>
      					    <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
                      <% if user_signed_in? %>
                        <% if (review.user == current_user) || (current_user.admin?) %>
                          <%= link_to "Edit", edit_store_review_path(@store, review) %>
                          <%= link_to "Delete", store_review_path(@store, review), method: :delete %>
                         <% end %>
                     <% end %>
      					  </td>
     				 </tr>
  				  <% end %>
 				 </tbody>
			</table>
		</div>
		<% end %>
	</div>
</div>


<%= link_to 'Edit', edit_store_path(@store), class: "btn btn-link"  %> |
<%= link_to 'Back', stores_path, class: "btn btn-link"  %>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/seattlecannabisguide/stars/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>